#########################################################
# This file defines all the needed configurations for this project

project_name: &project_name
  project: "MountainCarContinuous-v0 using SAC"

training_configs: &training_configs
  optimizer: Adam    # was a try at 14.Nov.2023
  learning_rate: 3.0e-4
  batch_size: &batch_size 64
  plan_length: 0
  epsilon_threshold: 0.1    # this is the initial value of epsilon and will be updated during training
  eta: 0.002    # for target network update (the same as in SAC)
  alpha: 0.1    # temperature term for cross entropy
  gamma: 0.98   # decay factor to stabilize Q values
  reward_scale: 1.0   # scaling factor for reward
  logging_frequency: 1000  # log every logging_frequency steps
  max_steps: 101000
  commentary:

neural_network_configs: &neural_network_configs
  hidden_layer_size: 256
  hidden_layer_number: 2
  device: &device
    "cuda"
  random_seed: null
  activation_function: "ReLU"
  enhance_mu: True
  gSDE: True

configs:
  Training:
    # name: "Training config"
    <<: *project_name
    <<: *training_configs

  Wandb:
    # name: "wandb.ai config"
    <<: *project_name
    config:
      <<: *training_configs
      <<: *neural_network_configs

  Env:
    # name: "env config"
    env_name: "MountainCarContinuous-v0"
    random_seed: null

    wrapper_ImageChannelFirst: True
    wrapper_RescaleAction: True
    wrapper_RescaleAction_min: -1
    wrapper_RescaleAction_max: 1
    wrapper_ContinuousActionClip: True
    wrapper_AutoReset: True
    render_mode: "human"

  NeuralNetwork:
    # name: "neural network config"
    <<: *neural_network_configs

  ReplayBuffer:
    # name: "Replay Buffer"
    buffer_size: 100000
    batch_size: *batch_size
    device: *device
